In [20]:
import numpy as np
################
# ACTIVITY ONE #
################
'''
  0 1 2 3 4
0|_|_|_|_|_|
1|S|_|_|_|G|
2|_|_|_|_|_|
'''
x = (0, 1, 2, 3, 4)
y = (0, 1, 3)

state_space = []
for i in range(len(y)):
    for j in range(len(x)):
        state = (i,j)
        state_space.append(state)
print(state_space)

start = state_space[1]
goal  = state_space[13]

action_space = ("UP", "DOWN", "LEFT", "RIGHT")

cost = np.ones((len(state_space), len(action_space)))

cost[14,0]  = 0 # position below Goal -> action UP
cost[4, 1] = 0 # position above Goal -> action DOWN
cost[13,3]  = 0 # position below to the left -> action UP

print(cost)

[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4)]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  0.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  0.]
 [ 0.  1.  1.  1.]]


In [30]:
################
# ACTIVITY TWO #
################


# FIRST ACTION: Right
print("FIRST ACTION: Right")
print("initial state: ", start)
print("action: ", action_space[3])
print("cost: ", 1)
print("next state: ", state_space[1])

# SECOND ACTION: Right
print("\nSECOND ACTION: Right")
print("state: ", state_space[1])
print("action: ", action_space[3])
print("cost: ", 1)
print("next state: ", state_space[2])

def func(*args):
    print(args)
    print(args[0])
    
func(1)

func(1, 2, 3, 4)

FIRST ACTION: Right
initial state:  (0, 1)
action:  RIGHT
cost:  1
next state:  (0, 1)

SECOND ACTION: Right
state:  (0, 1)
action:  RIGHT
cost:  1
next state:  (0, 2)
(1,)
1
(1, 2, 3, 4)
1
