In [3]:
# TPC Lab 2

# alinea C

import numpy as np

x = 0.1667

monopoly = np.array([[0, x, x , x, x, x, x, 0],
               [0, 0, x, x, x, x, x, x],
               [x, 0, 0, x, x, x, x, x],
               [x, x, 0, 0, x, x, x, x],
               [x, x, x, 0, 0, x, x, x],
               [x, x, x, x, 0, 0, x, x],
               [0, 0, 1, 0, 0, 0, 0, 0],
               [x, x, x, x, x, x, 0, 0]])

print(monopoly)

C = np.dot(monopoly, monopoly)
print ("\n\n\n", C)
B = np.linalg.matrix_power(monopoly, 3)

print("\n\n\n", B)

np.linalg.eig(monopoly)

[[ 0.      0.1667  0.1667  0.1667  0.1667  0.1667  0.1667  0.    ]
 [ 0.      0.      0.1667  0.1667  0.1667  0.1667  0.1667  0.1667]
 [ 0.1667  0.      0.      0.1667  0.1667  0.1667  0.1667  0.1667]
 [ 0.1667  0.1667  0.      0.      0.1667  0.1667  0.1667  0.1667]
 [ 0.1667  0.1667  0.1667  0.      0.      0.1667  0.1667  0.1667]
 [ 0.1667  0.1667  0.1667  0.1667  0.      0.      0.1667  0.1667]
 [ 0.      0.      1.      0.      0.      0.      0.      0.    ]
 [ 0.1667  0.1667  0.1667  0.1667  0.1667  0.1667  0.      0.    ]]



 [[ 0.11115556  0.08336667  0.25006667  0.08336667  0.08336667  0.11115556
   0.13894445  0.13894445]
 [ 0.13894445  0.11115556  0.25006667  0.08336667  0.08336667  0.11115556
   0.11115556  0.11115556]
 [ 0.11115556  0.13894445  0.27785556  0.08336667  0.08336667  0.11115556
   0.11115556  0.08336667]
 [ 0.08336667  0.11115556  0.30564445  0.11115556  0.08336667  0.11115556
   0.11115556  0.08336667]
 [ 0.08336667  0.08336667  0.27785556  0.13894445  0.11

(array([ 1.00017454+0.j        , -0.34198241+0.08727271j,
        -0.34198241-0.08727271j, -0.08386008+0.21501224j,
        -0.08386008-0.21501224j,  0.08755552+0.j        ,
        -0.11802254+0.06738842j, -0.11802254-0.06738842j]),
 array([[ 0.35355888+0.j        ,  0.13046124+0.22564279j,
          0.13046124-0.22564279j, -0.31123609-0.32169352j,
         -0.31123609+0.32169352j,  0.24663164+0.j        ,
         -0.09343937+0.05407275j, -0.09343937-0.05407275j],
        [ 0.35356032+0.j        , -0.07189071+0.17090177j,
         -0.07189071-0.17090177j,  0.18804918-0.1556452j ,
          0.18804918+0.1556452j , -0.29628135+0.j        ,
         -0.13896232-0.00479862j, -0.13896232+0.00479862j],
        [ 0.35356012+0.j        , -0.20533323+0.05240032j,
         -0.20533323-0.05240032j, -0.05391304+0.13822981j,
         -0.05391304-0.13822981j,  0.05967393+0.j        ,
          0.01018879-0.00967153j,  0.01018879+0.00967153j],
        [ 0.35356014+0.j        , -0.26206528-0.0885456